<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALv8tmL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALv8tmL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerALv8tmL.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerALv8tmL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerALv8tmL\appAppKernelProdContainer([
    'container.build_hash' => 'ALv8tmL',
    'container.build_id' => 'e9e33bcb',
    'container.build_time' => 1718776345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALv8tmL');
